window.request = {"variables":{"page":{"tenant":"ad","slug":"melhores-ofertas","siteEdition":"pt"},"id":"6509bb6f61285648c409de19","pageNumber":1,"limit":5,"flatContext":{"templateId":"6232e481fe2bcb1d00002c49","templateName":"home"},"filters":{"origin":null},"urlParameters":{}},"query":"query ($page: PageInput!, $id: String!, $pageNumber: Int, $limit: Int, $flatContext: FlatContextInput, $urlParameters: StandardFareModuleUrlParameters, $filters: StandardFareModuleFiltersInput) {\n  standardFareModule(page: $page, id: $id, pageNumber: $pageNumber, limit: $limit, flatContext: $flatContext, urlParameters: $urlParameters, filters: $filters) {\n    id\n    metaData {\n      name\n      title\n      footer\n      viewType\n      __typename\n    }\n    visualizationSettings {\n      includeImages\n      numberOfColumns\n      textAlignment\n      showJourneyType\n      showTravelClass\n      showFareTimestamp\n      showDates\n      carouselVisualizationType\n      __typename\n    }\n    filterSettings {\n      showOriginFilter\n      showDestinationFilter\n      showBudgetFilter\n      showTravelClassFilter\n      showBrandedTravelClassFilter\n      locationAttributesFilters\n      validateOriginsCountryMarket\n      currencyCode\n      restrictOriginFilter\n      restrictDestinationFilter\n      showRedemptionUnitFilter\n      __typename\n    }\n    filterRestrictions {\n      origin {\n        geoId\n        type\n        __typename\n      }\n      destination {\n        geoId\n        type\n        __typename\n      }\n      __typename\n    }\n    prepopulationSettings {\n      originAirportCode\n      destinationAirportCode\n      budgetMaximumAmount\n      travelClass\n      brandedTravelClasses\n      locationAttributes {\n        categoryId\n        tags\n        __typename\n      }\n      redemptionUnit\n      __typename\n    }\n    pagination {\n      currentPage\n      from\n      to\n      lastPage\n      itemsPerPage\n      total\n      __typename\n    }\n    fares(pageNumber: $pageNumber, limit: $limit, urlParameters: $urlParameters) {\n      image\n      originCity\n      destinationCity\n      usdTotalPrice\n      currencyCode\n      currencySymbol\n      originAirportCode\n      destinationAirportCode\n      formattedTravelClass\n      travelClass\n      brandedFareClass\n      farenetTravelClass\n      departureDate\n      formattedDepartureDate\n      returnDate\n      formattedReturnDate\n      flightType\n      formattedFlightType\n      priceLastSeen {\n        value\n        unit\n        __typename\n      }\n      redemption {\n        unit\n        amount\n        taxAmount\n        category\n        formattedTaxAmount\n        formattedAmount\n        shortenedFormattedTaxAmount\n        formattedTaxAmount\n        __typename\n      }\n      formattedTotalPrice\n      totalPrice\n      promoCode\n      __typename\n    }\n    error\n    __typename\n  }\n}\n"}


window.formatar = function formatDate(dateStr) {
  // Cria um objeto Date a partir da string de data no formato dd/mm/yyyy
  const [day, month, year] = dateStr.split("/");
  const date = new Date(year, month - 1, day);

  // Formata a data no formato mm/dd/yyyy
  const formattedDate = `${String(date.getMonth() + 1).padStart(2, '0')}/${String(date.getDate()).padStart(2, '0')}/${date.getFullYear()}`;

  return formattedDate;
}
